import type { Project, Service } from "@/lib/api";
// Published project failures must never substitute invented commercial evidence.
export const fallbackProjects: Project[] = [];
// Source-controlled service descriptions are an intentional part of the offering.
export const fallbackServices: Service[] = [
  { id: "service-power-bi", slug: "power-bi-dashboards", title: "Power BI dashboards", short_description: "Bring important metrics into a focused, interactive report.", sort_order: 1, is_active: true, full_description: "A reporting workflow from data preparation and KPI definitions to a usable Power BI report. We agree the questions, source data, and deliverables before work begins.", problems_solved: ["Metrics spread across spreadsheets", "Reports that are difficult to explore", "Inconsistent KPI definitions"], deliverables: ["Power BI report and data model", "Documented KPI definitions", "Refresh and handover guidance"], technologies: ["Power BI", "DAX", "Power Query"], process_steps: [{ title: "Define", description: "Agree the business questions, data sources, and acceptance criteria." }, { title: "Build", description: "Prepare the data, model the relationships, and review the first report." }, { title: "Validate & hand over", description: "Reconcile key totals and document refresh and usage." }] },
  { id: "service-data-cleaning", slug: "data-cleaning", title: "SQL & data preparation", short_description: "Make messy files and disconnected tables ready for analysis.", sort_order: 2, is_active: true, full_description: "A documented preparation process for spreadsheets, exports, and database tables. The scope depends on source quality, volume, and the questions the data must answer.", problems_solved: ["Duplicates and inconsistent formats", "Unclear joins and missing values", "Manual merging and cleanup"], deliverables: ["Prepared dataset and reusable queries", "Data-quality checks", "A record of assumptions and transformations"], technologies: ["SQL", "Python", "Pandas", "Excel"], process_steps: [{ title: "Inspect", description: "Review the schema, quality issues, and intended use." }, { title: "Prepare", description: "Build repeatable transformations and document exceptions." }, { title: "Check", description: "Validate counts, totals, and join behavior before handover." }] },
  { id: "service-report-automation", slug: "report-automation", title: "Reporting automation", short_description: "Turn repeated reporting steps into a consistent workflow.", sort_order: 3, is_active: true, full_description: "Repeatable reporting scripts with clear inputs, validation, and outputs. Scheduling and deployment are agreed around the environment where the workflow will run.", problems_solved: ["Repeated copy-and-paste reporting", "Inconsistent refresh steps", "Unclear failures or missing outputs"], deliverables: ["Reusable reporting script", "Validation and error reporting", "Setup, scheduling, and recovery instructions"], technologies: ["Python", "SQL", "CSV / Excel"], process_steps: [{ title: "Map", description: "Identify the manual steps and expected output." }, { title: "Automate", description: "Implement the workflow with checks and useful failure messages." }, { title: "Document", description: "Explain how to run, schedule, and recover the workflow." }] },
];
