import { Link } from "@tanstack/react-router";
import { ArrowUpRight } from "lucide-react";
import type { Project } from "@/lib/api";
const narratives: Record<
  string,
  { question: string; evidence: string; decision: string; limit: string }
> = {
  "pitchside-pro-revenue-performance-dashboard": {
    question: "Where should a growing ecommerce business focus?",
    evidence:
      "The report brings revenue, gross margin, product mix, and event timing into three connected views.",
    decision:
      "Start with a category, region, and channel hypothesis. Compare its margin and demand before committing to a growth test.",
    limit:
      "Dataset totals describe the study, not revenue generated by my work. Event associations are not causal estimates.",
  },
  "enron-emails-dataset-analysis": {
    question: "What changes when you count messages, rather than recipients?",
    evidence:
      "SQL separates distinct messages from recipient rows and checks membership against an employee roster.",
    decision:
      "Establish the counting grain before interpreting communication patterns. The reviewed SQL and reproduction notes are available in the case study.",
    limit:
      "The original database is not bundled, so full-corpus numerical results cannot be independently recomputed from the repository alone.",
  },
  "reporting-automation-pipeline": {
    question: "Can the same reporting workflow run twice without double-counting?",
    evidence:
      "A runnable Python example validates incoming files, records rejected rows, and tracks previously processed inputs.",
    decision:
      "Make reruns and failures explicit. The example includes regression checks and recovery instructions.",
    limit:
      "A small synthetic demonstration of workflow behavior, not a production warehouse or a claimed commercial result.",
  },
};
export function EditorialWork({
  projects,
  unavailable = false,
}: {
  projects: Project[];
  unavailable?: boolean;
}) {
  return (
    <section className="section editorial-work" id="selected-work">
      <div className="container">
        <div className="section-heading">
          <div>
            <p className="eyebrow">Selected work / The reasoning behind it</p>
            <h2>
              Different questions.
              <br />A considered approach.
            </h2>
          </div>
          <Link to="/projects" className="text-link">
            All projects <ArrowUpRight size={17} />
          </Link>
        </div>
        {projects.length ? (
          projects.slice(0, 3).map((p, i) => {
            const story = narratives[p.slug];
            return (
              <article
                className={"editorial-project " + (i === 0 ? "editorial-flagship" : "")}
                key={p.id}
              >
                <div className="editorial-project-title">
                  <span className="eyebrow">
                    0{i + 1} / {p.study_type || "Portfolio study"}
                  </span>
                  <h3>
                    <Link to="/projects/$slug" params={{ slug: p.slug }}>
                      {story?.question || p.title}
                    </Link>
                  </h3>
                  <p className="editorial-tools">{p.technologies.slice(0, 4).join(" / ")}</p>
                </div>
                <div className="editorial-project-body">
                  {p.image_url && (
                    <Link
                      to="/projects/$slug"
                      params={{ slug: p.slug }}
                      className="editorial-image"
                    >
                      <img
                        src={p.image_url}
                        srcSet={p.image_srcset}
                        sizes="(max-width: 760px) 92vw, 65vw"
                        alt={p.title}
                        width="1200"
                        height="750"
                        loading="lazy"
                        decoding="async"
                      />
                    </Link>
                  )}
                  <div className="editorial-reasoning">
                    <div>
                      <h4>The evidence</h4>
                      <p>{story?.evidence || p.short_description}</p>
                    </div>
                    <div>
                      <h4>The decision</h4>
                      <p>{story?.decision || p.recommendation || p.contribution}</p>
                    </div>
                  </div>
                  <p className="editorial-limit">
                    <strong>Scope note.</strong>{" "}
                    {story?.limit || p.limitations?.[0] || p.source_note}
                  </p>
                  <Link to="/projects/$slug" params={{ slug: p.slug }} className="text-link">
                    {i === 0 ? "Walk through the flagship study" : "Explore the study"}
                    <ArrowUpRight size={17} />
                  </Link>
                </div>
              </article>
            );
          })
        ) : (
          <div className="empty-state">
            <h3>
              {unavailable
                ? "Project evidence is temporarily unavailable"
                : "Project studies are being prepared"}
            </h3>
            <a href="https://github.com/zainhaidar16" className="text-link">
              Explore the repositories on GitHub ↗
            </a>
          </div>
        )}
      </div>
    </section>
  );
}
