import type { Project } from "@/lib/api";
import { safeUrl } from "@/lib/seo";
const details: Record<string, Partial<Project>> = {
  "pitchside-pro-revenue-performance-dashboard": {
    title: "Pitchside Pro: revenue performance", hero_title: "What is driving revenue—and where should the business focus?",
    short_description: "An executive Power BI report connecting revenue, margin, seasonality, and product performance.",
    hero_description: "A three-page ecommerce analysis that moves from performance overview to timing patterns and growth priorities.",
    contribution: "Data preparation, Power BI modeling, DAX measures, and report design.",
    source_note: "Football ecommerce data covering revenue, profit, traffic, products, channels, and event timing. The figures below describe the report’s dataset.",
    period_note: "Explore the year and category filters in the interactive report.",
    findings: [
      { title: "Revenue and profit tell different stories", detail: "The report shows $11.2M net revenue, $5.9M gross profit, and a 52.8% gross margin. Evaluating margin alongside revenue helps distinguish sales scale from gross profitability." },
      { title: "Event timing deserves a closer look", detail: "$6.3M is classified as football-moment revenue—approximately 56% of the displayed total. This identifies a concentration to investigate; it does not establish that events caused those sales." },
      { title: "A specific growth hypothesis", detail: "The report highlights Kits, EMEA, and Web as growth priorities. Compare their margins, demand patterns, and capacity before deciding where to invest." },
    ],
    recommendation: "Use the category, region, and channel views to define a focused growth test. Compare a baseline period with the test period and track gross margin as well as revenue.",
    limitations: ["Revenue and profit are dataset totals, not revenue generated by this project.", "Event-linked revenue indicates association, not a causal uplift estimate.", "The report’s growth-runway figure is a scenario estimate, not realized growth. Its assumptions must be established before using it as a forecast.", "Displayed totals are rounded; reconcile calculations against underlying measures before financial planning."],
  },
  "insurance-claims-analysis-dashboard": {
    title: "Insurance claims: patterns behind the totals", hero_title: "Understanding insurance claims across people, vehicles, and coverage.",
    short_description: "An interactive Power BI study of claim amounts, claim frequency, and coverage across demographic and vehicle groups.",
    contribution: "Data preparation, DAX measures, and three report pages for demographic, claim, and financial analysis.",
    source_note: "The report combines car-insurance claims, demographic, vehicle, and financial fields. Figures describe the analyzed dataset.",
    findings: [
      { title: "Coverage mix is uneven", detail: "The report shows an 80% private / 20% commercial insurance split. Compare normalized claim rates rather than treating raw group totals as directly comparable." },
      { title: "Scale and frequency are separate questions", detail: "The displayed dataset includes about 38K customers and 19K claims. Claim amounts and claim frequency should be reviewed together when comparing segments." },
      { title: "Explore beyond the headline total", detail: "Demographic, vehicle, and income filters allow a reviewer to inspect how the composition of a group changes the reported totals." },
    ],
    recommendation: "Normalize segment comparisons by exposure and review data completeness before interpreting a higher total as a higher risk.",
    limitations: ["This is exploratory reporting, not a validated risk or pricing model.", "Demographic associations do not establish causes and should not alone determine individual eligibility or pricing.", "The report’s totals and averages need consistent filter context when comparing groups."],
  },
  "enron-emails-dataset-analysis": {
    title: "Enron emails: SQL and communication patterns", contribution: "SQL querying, Python exploration, and text analysis in a reproducible notebook.",
    source_note: "Public Enron email corpus. Consult the repository for the database setup and source attribution.",
    limitations: ["Historical email coverage is incomplete and does not represent all communication.", "Message counts and recipient counts have different grains; multiple recipients must not multiply the message total.", "Common words and message frequency do not establish intent or wrongdoing."],
  },
  "telco-customer-churn-prediction": {
    title: "Telco churn: a classification workflow", technologies: ["Python", "Pandas", "TensorFlow", "Keras", "Streamlit"],
    short_description: "A Python application for exploring customer churn modeling and evaluation.",
    limitations: ["Training accuracy does not establish performance on unseen customers.", "A retention threshold needs an explicit cost/benefit assumption; a score alone is not an operational recommendation."],
  },
};
export function curateProject(project: Project): Project {
  const curated = { ...project, study_type: "Portfolio study", ...details[project.slug] };
  return {
    ...curated,
    metrics: curated.metrics.filter(metric => !/growth runway/i.test(metric.label)),
    image_url: safeUrl(curated.image_url), live_url: safeUrl(curated.live_url), github_url: safeUrl(curated.github_url),
    gallery: curated.gallery?.filter(image => safeUrl(image.image_url)).map(image => ({ ...image, image_url: safeUrl(image.image_url)! })),
  };
}
export function selectFeatured(projects: Project[]) {
  const order = ["pitchside-pro-revenue-performance-dashboard", "enron-emails-dataset-analysis", "reporting-automation-pipeline", "insurance-claims-analysis-dashboard"];
  return order.map(slug => projects.find(project => project.slug === slug)).filter((project): project is Project => Boolean(project)).slice(0, 3);
}
