import type { Project } from "@/lib/api";
import { safeUrl } from "@/lib/seo";
const details: Record<string, Partial<Project>> = {
  "pitchside-pro-revenue-performance-dashboard": {
    title: "Pitchside Pro: revenue performance",
    hero_title: "What is driving revenue—and where should the business focus?",
    short_description:
      "An executive Power BI report connecting revenue, margin, seasonality, and product performance.",
    hero_description:
      "A three-page ecommerce analysis that moves from performance overview to timing patterns and growth priorities.",
    contribution: "Data preparation, Power BI modeling, DAX measures, and report design.",
    source_note:
      "Football ecommerce data covering revenue, profit, traffic, products, channels, and event timing. The figures below describe the report’s dataset.",
    period_note: "Explore the year and category filters in the interactive report.",
    findings: [
      {
        title: "Revenue and profit tell different stories",
        detail:
          "The report shows $11.2M net revenue, $5.9M gross profit, and a 52.8% gross margin. Evaluating margin alongside revenue helps distinguish sales scale from gross profitability.",
      },
      {
        title: "Event timing deserves a closer look",
        detail:
          "$6.3M is classified as football-moment revenue—approximately 56% of the displayed total. This identifies a concentration to investigate; it does not establish that events caused those sales.",
      },
      {
        title: "A specific growth hypothesis",
        detail:
          "The report highlights Kits, EMEA, and Web as growth priorities. Compare their margins, demand patterns, and capacity before deciding where to invest.",
      },
    ],
    recommendation:
      "Use the category, region, and channel views to define a focused growth test. Compare a baseline period with the test period and track gross margin as well as revenue.",
    limitations: [
      "Revenue and profit are dataset totals, not revenue generated by this project.",
      "Event-linked revenue indicates association, not a causal uplift estimate.",
      "The report’s growth-runway figure is a scenario estimate, not realized growth. Its assumptions must be established before using it as a forecast.",
      "Displayed totals are rounded; reconcile calculations against underlying measures before financial planning.",
    ],
  },
  "insurance-claims-analysis-dashboard": {
    title: "Insurance claims: patterns behind the totals",
    hero_title: "Understanding insurance claims across people, vehicles, and coverage.",
    short_description:
      "An interactive Power BI study of claim amounts, claim frequency, and coverage across demographic and vehicle groups.",
    contribution:
      "Data preparation, DAX measures, and three report pages for demographic, claim, and financial analysis.",
    source_note:
      "The report combines car-insurance claims, demographic, vehicle, and financial fields. Figures describe the analyzed dataset.",
    findings: [
      {
        title: "Coverage mix is uneven",
        detail:
          "The report shows an 80% private / 20% commercial insurance split. Compare normalized claim rates rather than treating raw group totals as directly comparable.",
      },
      {
        title: "Scale and frequency are separate questions",
        detail:
          "The displayed dataset includes about 38K customers and 19K claims. Claim amounts and claim frequency should be reviewed together when comparing segments.",
      },
      {
        title: "Explore beyond the headline total",
        detail:
          "Demographic, vehicle, and income filters allow a reviewer to inspect how the composition of a group changes the reported totals.",
      },
    ],
    recommendation:
      "Normalize segment comparisons by exposure and review data completeness before interpreting a higher total as a higher risk.",
    limitations: [
      "This is exploratory reporting, not a validated risk or pricing model.",
      "Demographic associations do not establish causes and should not alone determine individual eligibility or pricing.",
      "The report’s totals and averages need consistent filter context when comparing groups.",
    ],
  },
  "enron-emails-dataset-analysis": {
    study_type: "Public-data study",
    evidence_links: [
      {
        label: "Reviewed message-count SQL",
        url: "/project-artifacts/enron/communication_scope.sql",
      },
      { label: "Reproduction notes & limitations", url: "/project-artifacts/enron/README.md" },
    ],
    title: "Enron emails: SQL and communication patterns",
    contribution: "SQL querying, Python exploration, and text analysis.",
    source_note:
      "Historical Enron email corpus. The original SQLite database is not bundled; full corpus results require that source database.",
    limitations: [
      "Historical email coverage is incomplete and does not represent all communication.",
      "Message counts and recipient counts have different grains; multiple recipients must not multiply the message total.",
      "Common words and message frequency do not establish intent or wrongdoing.",
    ],
  },
  "telco-customer-churn-prediction": {
    study_type: "Modeling study",
    github_url: "https://github.com/zainhaidar16/teleco-customer-churn-prediction",
    live_url: undefined,
    gallery: [],
    contribution:
      "A churn classification workflow with training-only preprocessing, an independent test split, and a simple comparison baseline.",
    source_note:
      "The bundled Telco CSV contains 7,043 customer rows. This evaluation uses 5,634 training rows and 1,409 test rows with a stratified split and seed 42. Dataset acquisition and reuse terms still need documentation.",
    evidence_links: [
      { label: "Evaluation code", url: "/project-artifacts/telco/churn_model.py" },
      { label: "Saved test results", url: "/project-artifacts/telco/evaluation.json" },
      { label: "Reproduction instructions", url: "/project-artifacts/telco/README.md" },
      { label: "Regression tests", url: "/project-artifacts/telco/test_churn_model.py" },
      {
        label: "Original project repository",
        url: "https://github.com/zainhaidar16/teleco-customer-churn-prediction",
      },
    ],
    approach: [
      "Validate labels and reject duplicate customer IDs before splitting.",
      "Hold out a stratified 20% test set. Fit imputation, scaling, category encoding, and logistic regression using training rows only.",
      "Evaluate at a fixed 0.50 threshold and compare with a class-prior baseline.",
    ],
    solution_steps: [],
    findings: [
      {
        title: "Ranking improves on the baseline",
        detail:
          "Test average precision is 0.634 versus 0.265 for the class-prior baseline. The positive-class prevalence is 26.5%, providing context for the comparison.",
      },
      {
        title: "The threshold leaves a clear tradeoff",
        detail:
          "At a 0.50 threshold, precision is 65.7% and recall is 55.9%. The test confusion matrix contains 209 true positives, 109 false positives, and 165 missed churn cases.",
      },
      {
        title: "Accuracy is only part of the picture",
        detail:
          "Test accuracy is 80.6%, compared with 73.5% for the prior baseline. That baseline identifies no churn cases at the same threshold, illustrating why accuracy alone is insufficient.",
      },
    ],
    recommendation:
      "Before a retention pilot, select a threshold on separate validation data using intervention cost, expected saved margin, and treatment effectiveness. Keep the test set out of that selection process.",
    title: "Telco churn: a classification workflow",
    technologies: ["Python", "Pandas", "Scikit-learn", "Streamlit"],
    short_description: "A Python application for exploring customer churn modeling and evaluation.",
    limitations: [
      "A single random holdout does not establish performance across future periods or different populations.",
      "A retention threshold needs an explicit cost/benefit assumption; a score alone is not an operational recommendation.",
    ],
  },
};
export function curateProject(project: Project): Project {
  const curated = { ...project, study_type: "Portfolio study", ...details[project.slug] };
  const optimized = [
    "pitchside-pro-revenue-performance-dashboard",
    "insurance-claims-analysis-dashboard",
    "enron-emails-dataset-analysis",
  ].includes(project.slug);
  const thumbnail = "/project-images/optimized/" + project.slug;
  return {
    ...curated,
    metrics: curated.metrics.filter((metric) => !/growth runway/i.test(metric.label)),
    image_url: optimized ? thumbnail + "-1200.webp" : safeUrl(curated.image_url),
    image_srcset: optimized
      ? thumbnail + "-600.webp 600w, " + thumbnail + "-1200.webp 1200w"
      : undefined,
    live_url: safeUrl(curated.live_url),
    github_url: safeUrl(curated.github_url),
    gallery: curated.gallery
      ?.filter((image) => safeUrl(image.image_url))
      .map((image) => ({ ...image, image_url: safeUrl(image.image_url)! })),
  };
}
export function selectFeatured(projects: Project[]) {
  const order = [
    "pitchside-pro-revenue-performance-dashboard",
    "enron-emails-dataset-analysis",
    "reporting-automation-pipeline",
    "insurance-claims-analysis-dashboard",
  ];
  return order
    .map((slug) => projects.find((project) => project.slug === slug))
    .filter((project): project is Project => Boolean(project))
    .slice(0, 3);
}
